# Generated by Django 3.0.8 on 2020-08-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_customuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='profile_image',
        ),
    ]
