# Generated by Django 3.0.8 on 2020-08-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
