# Generated by Django 3.0.8 on 2020-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
