# Generated by Django 3.0.8 on 2020-08-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0012_post_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
